export const services = {
  "website-design-jodhpur": {
    name: "Website Design & Development",
    eyebrow: "JODHPUR / WEB DESIGN",
    title: "Website design in Jodhpur, built around the business behind it.",
    metaTitle: "Website Design in Jodhpur | TENZO STUDIO",
    metaDescription: "TENZO STUDIO designs and builds websites for Jodhpur businesses. Clear structure, considered design, responsive development, and a route from visit to enquiry.",
    summary: "A serious business needs more than an online brochure. We shape the content, interface, and enquiry path into one coherent website.",
    opening: [
      "Your site should make the right first impression and help a visitor take the next step. That means defining what the business offers, who it serves, why it is credible, and how a prospective client should make contact before deciding on a visual direction.",
      "TENZO STUDIO is based in Jodhpur. We work with local businesses and professionals that need a clear, credible digital presence, as well as founders building for wider markets. Each website begins with the actual scope: a focused launch site, a service-led site, or a more connected digital system.",
    ],
    needs: [
      { title: "A first credible website", body: "You have a strong service but no clear place to explain it, answer buyer questions, and receive qualified enquiries." },
      { title: "A site that no longer reflects the business", body: "The business has moved forward, while its navigation, copy, design, or mobile experience still describes an earlier version." },
      { title: "A better enquiry path", body: "Visitors can find the site but cannot quickly understand the offer, see relevant proof, or choose a sensible next step." },
    ],
    deliverables: [
      "Discovery and a written scope tied to the business goal",
      "Page hierarchy, content structure, and clear calls to action",
      "Responsive interface design and development",
      "Performance, accessibility, and search-ready foundations",
      "Contact, booking, CRM, or workflow integration when the project requires it",
    ],
    approach: [
      { title: "Define", body: "We map the buyer, the offer, required pages, existing assets, and the action the site must support." },
      { title: "Design and build", body: "Content, visual hierarchy, mobile layouts, and engineering are developed against the same brief." },
      { title: "Review and launch", body: "We test key paths, resolve the agreed revisions, and hand over a site that can be maintained." },
    ],
    local: "For a Jodhpur buyer, local relevance should come from real context: the service you provide here, genuine project evidence, and accurate ways to contact you. A city name repeated across empty pages does not create trust. TENZO's Jodhpur base informs the working relationship; your own site should make your business equally clear to its customers.",
    fit: "Useful for clinics, hospitality businesses, consultants, service firms, and founders who want their website to reflect the standard of their work. The final page count and integrations depend on discovery.",
    question: "What should we prepare before a website project?",
    answer: "Bring your current site if you have one, the services you need to explain, existing brand assets, examples of customer questions, and the outcome you want from enquiries. Missing material can be scoped into the project.",
    moreQuestions: [
      { question: "How is the cost of a website decided?", answer: "The scope changes with the number and type of pages, content work, design complexity, integrations, and maintenance needs. We review those factors before proposing a price; a fixed quote without a defined brief would be misleading." },
      { question: "What happens after the site launches?", answer: "We check the agreed pages, contact path, mobile layouts, and search foundations before handover. Any continuing maintenance, analytics, or automation work is defined in the project scope rather than assumed." },
    ],
    related: ["brand-identity-jodhpur", "product-design-ai-mvps"],
    localService: true,
  },
  "brand-identity-jodhpur": {
    name: "Brand Identity & Systems",
    eyebrow: "JODHPUR / BRAND IDENTITY",
    title: "Brand identity in Jodhpur with a system behind every decision.",
    metaTitle: "Brand Identity Design in Jodhpur | TENZO STUDIO",
    metaDescription: "TENZO STUDIO develops brand identity systems for Jodhpur businesses: positioning, visual language, guidelines, and applications that work together.",
    summary: "A stronger brand is a set of decisions people can recognize and your team can use consistently. We build that system from the core outward.",
    opening: [
      "A logo cannot carry every interaction your business has with the market. Identity needs a clear point of view, a visual language, and rules that survive beyond the launch deck.",
      "TENZO begins with what the business stands for and how it needs to be understood. We then translate that direction into usable design decisions across website, social, campaign, and physical touchpoints as the scope requires.",
    ],
    needs: [
      { title: "Inconsistent presence", body: "Your website, sales material, and social content look like separate businesses because there is no shared system." },
      { title: "A business that has outgrown its identity", body: "The offer or audience has changed, but the existing brand still signals the old position." },
      { title: "A new venture needing a foundation", body: "You need a clear identity before investing in a website, content production, and campaigns." },
    ],
    deliverables: [
      "Brand discovery and positioning direction",
      "Visual identity and typography/color system",
      "Application examples for agreed customer touchpoints",
      "Guidelines that make future execution consistent",
      "Motion or sonic identity when those disciplines serve the brief",
    ],
    approach: [
      { title: "Understand", body: "We study the offer, audience, competitive context, and current brand signals." },
      { title: "Define", body: "We establish the principles that should guide recognition, tone, and visual decisions." },
      { title: "Systematize", body: "We build the identity and document how it works across the agreed applications." },
    ],
    local: "Jodhpur businesses compete on more than proximity. Customers compare the quality of a brand before they speak to anyone. We use the business's real audience and market context to shape an identity, without relying on stock local symbols or unsupported claims of being the city's best.",
    fit: "Useful for founders preparing a launch, established businesses repositioning, and service firms whose current visual presence no longer matches their work.",
    question: "Is this only a logo design project?",
    answer: "No. The identity is defined as a system. A narrower starting scope is possible, but the agreed deliverables must still support consistent use after handover.",
    moreQuestions: [
      { question: "Can an existing brand be refined without starting again?", answer: "Yes, if the underlying position still serves the business. We review what people already recognize, identify the gaps, and decide what should be kept, clarified, or redesigned." },
      { question: "What makes the identity usable after handover?", answer: "The agreed guidelines show how core elements behave across the relevant formats. Application examples make the rules concrete for whoever produces the next website page, campaign asset, or social post." },
    ],
    related: ["website-design-jodhpur", "visual-motion-design"],
    localService: true,
  },
  "social-media-jodhpur": {
    name: "Social Media & Growth Systems",
    eyebrow: "JODHPUR / SOCIAL SYSTEMS",
    title: "Social media systems for Jodhpur brands with something to say.",
    metaTitle: "Social Media Marketing in Jodhpur | TENZO STUDIO",
    metaDescription: "TENZO STUDIO connects social content, campaigns, creative systems, and measurement for Jodhpur brands. Define the audience and the outcome before posting.",
    summary: "A calendar of posts is not a growth strategy. We connect the message, creative format, distribution, and measurement to a defined business goal.",
    opening: [
      "The right social presence makes a brand easier to recognize and easier to trust. It should show a clear point of view, make useful ideas visible, and lead interested people toward a meaningful action.",
      "TENZO works across content systems, short-form motion, campaign creative, paid distribution, automation, and analytics when the scope calls for them. We decide which pieces belong together after understanding the audience and the current channel performance.",
    ],
    needs: [
      { title: "Inconsistent content", body: "Every post starts from zero because the brand has no repeatable themes, formats, or visual rules." },
      { title: "Activity without a clear outcome", body: "The team publishes often but cannot explain which audience or business action the content is meant to support." },
      { title: "Campaigns that feel disconnected", body: "Paid creative, organic social, website pages, and enquiry handling tell different stories." },
    ],
    deliverables: [
      "Audience, channel, and goal definition",
      "Content pillars and repeatable creative formats",
      "Visual and motion templates for the agreed channels",
      "Campaign planning or paid-media creative where included in scope",
      "Measurement framework and reporting decisions",
    ],
    approach: [
      { title: "Audit", body: "We assess the existing message, content, channels, and the action each channel should support." },
      { title: "Design the system", body: "We define formats, production rules, cadence, and how social connects to the website or enquiry path." },
      { title: "Learn", body: "We review meaningful signals and adjust the system rather than treating a posting schedule as the objective." },
    ],
    local: "Local relevance can come from real customer questions, true service context, and the way a Jodhpur business actually works. We avoid manufactured local proof, purchased engagement, and claims that every post will generate leads.",
    fit: "Useful for service brands, hospitality businesses, founders, and growing teams that need their social presence to express a consistent brand and support a defined commercial goal.",
    question: "Does TENZO offer social media management?",
    answer: "TENZO's growth and social work can include content systems, campaigns, automation, and measurement. Ongoing publishing or channel management should be agreed explicitly in the project scope.",
    moreQuestions: [
      { question: "Which social channels should a business use?", answer: "That depends on where the intended audience pays attention, what the business can produce consistently, and which action the channel should support. A smaller, coherent presence can be more useful than posting everywhere." },
      { question: "When should paid campaigns be part of the plan?", answer: "Paid distribution makes more sense when the offer, landing path, creative, and measurement are ready. We define the campaign objective and review the available budget before recommending a channel or spend." },
    ],
    related: ["brand-identity-jodhpur", "visual-motion-design"],
    localService: true,
  },
  "product-design-ai-mvps": {
    name: "Product Design & AI MVPs",
    eyebrow: "PRODUCT / UX / AI",
    title: "Turn a product hypothesis into a system you can test.",
    metaTitle: "Product Design & AI MVPs | TENZO STUDIO",
    metaDescription: "TENZO STUDIO shapes product strategy, user journeys, interface systems, prototypes, and AI integration plans for founders building an MVP.",
    summary: "An MVP should test the right assumption. We connect product decisions, user experience, engineering, and AI integration around that purpose.",
    opening: [
      "A founder does not need every feature they can imagine. They need a product architecture that makes the core value clear, exposes the largest risk, and can be built and evaluated in stages.",
      "TENZO works from the hypothesis through journeys, interface states, prototypes, and the technical decisions that shape a first release. Where AI has a useful role, we define the task, human controls, and system behavior before choosing tools.",
    ],
    needs: [
      { title: "A promising but broad idea", body: "The opportunity is clear, but the first release has no disciplined scope or testable user journey." },
      { title: "A product that is hard to explain", body: "Stakeholders see features, while the core workflow and value remain unclear." },
      { title: "AI added without a product reason", body: "The team needs to decide where automation genuinely helps and where users need explicit control." },
    ],
    deliverables: ["Problem and feature architecture", "User flows and interface states", "High-fidelity UX/UI design and interactive prototypes", "Design system foundations", "AI integration strategy where relevant"],
    approach: [
      { title: "Frame", body: "We define the user, job, constraints, and assumption the MVP is meant to test." },
      { title: "Architect", body: "We map flows, features, data, and the minimum useful release boundary." },
      { title: "Prototype and build", body: "We make the product tangible, review it against the hypothesis, and define the production path." },
    ],
    fit: "Useful for founders building a SaaS product, AI tool, B2B workflow, or digital service that needs sharper product decisions before or during development.",
    question: "Can TENZO design an AI MVP without adding AI everywhere?",
    answer: "Yes. AI should have a defined job in the experience. If a simpler workflow works better, that should shape the architecture instead.",
    related: ["website-design-jodhpur", "brand-identity-jodhpur"],
  },
  "visual-motion-design": {
    name: "Visual & Motion Design",
    eyebrow: "VISUAL / MOTION",
    title: "Motion and visual systems with a clear purpose.",
    metaTitle: "Visual & Motion Design | TENZO STUDIO",
    metaDescription: "TENZO STUDIO creates visual assets, motion language, 2D/3D illustration, and campaign visuals that support a consistent brand or product experience.",
    summary: "Movement can explain, direct attention, and make an idea memorable. It needs the same discipline as every other design decision.",
    opening: [
      "Visual impact is useful when it makes the message more legible. TENZO develops custom illustration, kinetic type, motion behavior, icons, and campaign assets as parts of a wider system.",
      "The work can support a website, product interface, brand identity, or launch campaign. We define where motion belongs, how it behaves across formats, and what should remain still.",
    ],
    needs: [
      { title: "A static brand that needs expression", body: "The identity is clear, but its behavior in digital media has not been defined." },
      { title: "A complex idea that needs explanation", body: "A product or service needs a visual narrative that helps people understand the essential idea." },
      { title: "Campaign assets without consistency", body: "Each asset is produced in isolation, slowing production and weakening recognition." },
    ],
    deliverables: ["Motion principles and interaction direction", "Kinetic typography or 2D/3D visual assets", "Custom iconography or illustration", "Campaign and launch creative", "Usage rules for the agreed formats"],
    approach: [
      { title: "Find the signal", body: "We identify what the visual needs to communicate and where the audience will see it." },
      { title: "Build the language", body: "We define composition, timing, movement, and asset rules." },
      { title: "Deliver for use", body: "We prepare the agreed outputs and guidance for their real contexts." },
    ],
    fit: "Useful for brands and products that already have a clear message and need a more distinctive way to express it across digital touchpoints.",
    question: "Is motion included in every website or brand project?",
    answer: "Only when it serves the brief. Motion should improve meaning or orientation, not add weight without purpose.",
    related: ["brand-identity-jodhpur", "website-design-jodhpur"],
  },
};

export const serviceSlugs = Object.keys(services);
